[package]
name = "sdl_test"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]

[dependencies]
sdl2 = "0.20"
rand = "*"
image = "*"
nalgebra = "*"
ecs = "*"
time = "*"

[dependencies.sdl2_ttf]
git = "https://github.com/andelf/rust-sdl2_ttf"
